Check for `dependent: :destroy_async` and a foreign key
gregnavis/active_record_doctor pull request #108
Opened 2022-07-15 21:41 UTC by fatkodima

Rails 6.1 [introduced](https://github.com/rails/rails/pull/40157) `dependent: :destroy_async` which allows to destroy associated records in the background. This is useful when the parent record has lots of associated records and destroying all of them in the same transaction can potentially take a lot of time and/or lead to long database locks.

From the [documentation](https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many):

> **WARNING**: Do not use this option if the association is backed by foreign key constraints in your database. The foreign key constraint actions will occur inside the same transaction that deletes its owner.  

So one can create a foreign key with `on_delete: :cascade` and an association with `dependent: :destroy_async` and when destroying the parent record, all the child records will be deleted/nullified immediately in the same transaction. This can run unnoticed for some time and blow up production later.

2022-12-07 13:35 UTC, gregnavis requested changes

2022-12-07 13:35 UTC, gregnavis commented on lib/active_record_doctor/detectors/incorrect_dependent_option.rb
> +              if foreign_key
It seems `foreign_key` can be inlined, however rewording the message may force use to keep that variable here. Leaving this up to you.

2022-12-07 13:35 UTC, gregnavis commented on lib/active_record_doctor/detectors/incorrect_dependent_option.rb
> +            "the foreign key actions will occur inside the same transaction that deletes its owner"
I suggest rewording that to:

```
don't use `dependent: :destroy_async` on #{model}.#{association} or remove the foreign key from #{table_name}.#{column_name} - associated models will be deleted in the same transaction along with #{model}
```

2022-12-07 13:54 UTC, fatkodima commented
Changed the message wording.

2022-12-07 14:02 UTC, gregnavis approved these changes

2023-04-01 13:32 UTC, gregnavis commented
@fatkodima, could you rebase it on top of `master`? Thanks!

2023-04-01 18:04 UTC, fatkodima commented
@gregnavis Rebased.

2023-04-13 12:02 UTC, gregnavis approved these changes

2023-04-13 12:03 UTC, merged