missing_non_null_constraint: ignore database views
gregnavis/active_record_doctor pull request #201
Opened 2024-12-17 21:42 UTC by fatkodima

Fixes #200.

2025-01-03 11:56 UTC, gregnavis commented
@fatkodima, I'll do some merging soon. Sorry, I've been dealing with some personal stuff.

2025-01-11 13:41 UTC, gregnavis requested changes
Thanks for the PR! I left some comments on the test case.

2025-01-11 13:41 UTC, gregnavis commented on test/active_record_doctor/detectors/missing_non_null_constraint_test.rb
> +    connection.execute("DROP VIEW comments")
Same as above - we should be able to replace this with `Context.execute`.

2025-01-11 13:47 UTC, fatkodima commented
Made changes.

2025-01-11 13:49 UTC, gregnavis commented
@fatkodima, your nickname should be "lightning" 😄  Thanks for the update. Let's see whether the CI is happy with the new version of `transient_record`.

2025-01-11 13:58 UTC, gregnavis approved these changes

2025-01-11 13:58 UTC, merged